targets:
  $default:
    builders:
      json_serializable:
        options:
          # Options for json_serializable
          explicit_to_json: true
          include_if_null: false
        generate_for:
          - lib/src/models/**.dart
